### ISSUE TITLE
[Action Cable] Suggestion: discuss cfapps.io vs custom domains

### ISSUE THREAD

**Issue by drnic** [pivotal/blog#137]
@DylanGriffith I found http://pivotal-cf-blog-staging.cfapps.io/post/using-action-cable-with-cloud-foundry/ via the wonders of Google. Thanks for writing it. Then found I can leave "comments" via github issues. Neat.

The changes in the second half of the blog post worked great for my demo actioncable app hosted at a *.cfapps.io route.

When I made the same changes to my production app hosted on a custom domain via cloudflare it didn't work.

In the browser the error looks like:

![](https://cl.ly/300O173K3j1Z/download/Image%202017-02-19%20at%203.21.53%20PM.png)

It turns out that custom domains hosted by cloudflare don't pass thru port 4443 https://support.cloudflare.com/hc/en-us/articles/200169156-Which-ports-will-Cloudflare-work-with-

Instead, I needed to add an additional `cfapps.io` route and change by `config/environments/production.rb` to only use it:

```ruby
  # Since PWS uses port 4443 (rather than 443) for websocket connections
  # Need to use a *.cfapps.io domain since custom domains via CloudFlare won't
  # pass port 4443
  # https://support.cloudflare.com/hc/en-us/articles/200169156-Which-ports-will-Cloudflare-work-with-
  if ENV['VCAP_APPLICATION'].present?
    application_uris = JSON.parse(ENV['VCAP_APPLICATION'])["application_uris"]
    if host = application_uris.find {|uri| uri =~ /cfapps.io/}
      config.action_cable.url = "wss://#{host}:4443/cable"
    else
      Rails.logger.error "Must deploy with a cfapps.io domain that supports :4443"
    end
    origins = application_uris.inject([]) do |uris, host|
      uris << "https://#{host}"
      uris << "http://#{host}"
      uris
    end
    Rails.application.config.action_cable.allowed_request_origins = origins
  end
```

Since the user will be going to the custom domain, we also need allowed_request_origins to allow those requests to flow into the xyz.cfapps.io:4443/cable url.

Perhaps include the following snippet above and/or explanation of "ensure your custom domain also allows :4443" "cloudflare does not pass 4443 to run.pivotal.io", etc

Thanks again for the post!

**Comment by DylanGriffith** [comment]
@drnic thanks for this. I think I understand what you're saying after reading this a couple of times but I'm not 100% sure the notes about CloudFlare are suitable in this blog post but I could be persuaded. I've never personally set up CloudFlare but wondering if it's going to be common for people to following these instructions to end up getting stuck because it's not supported on CloudFlare. I guess my concern would be that it would be those side notes might just be confusing and I guess I couldn't necessary cover all networking issues in this post as I was really just trying to already cover the complexity of this 4443 networking issue on CF. Also if somebody is adding proxies over the top of the PWS deployment they likely already know the implications this will have on their networking.

That being said I think your change about looping over all the application_uris is a good one. I will make that for now.

**Comment by DylanGriffith** [comment]
@drnic would you mind taking a look at https://github.com/pivotal/blog/commit/7d2e6a08074f872547d519c97c0b72d801bb284b and seeing if it addresses the information you wanted to convey?

**Comment by osis** [comment]
Looking at the comment on the commit. Looks like we're good on this? @DylanGriffith @drnic
