### ISSUE TITLE
Android-related info for "worlds-smallest-concourse-server"

### ISSUE THREAD

**Issue by equinoxel** [pivotal/blog#81]
Hi,

I'm looking at ConcourseCI to replace my (ailing?) Travis workflow. In your article, it's stated at step 0 that:

> In the following steps, we demonstrate creating a Concourse CI server, ci.blabbertabber.com for our open source Android project, BlabberTabber.

Unfortunately, the article ends just after setting the simple pipeline from the concourse tutorial. Do you have any plans to expand it with android-related information?

TIA,

Laur

**Comment by tsaleh** [comment]
@cunnie ⬆️

**Comment by cunnie** [comment]
Hi @equinoxel ,

I'm sorry to take so long getting back to you — I only recently discovered a cache of "lost" GitHub messages.

The short version is this: I don't plan on updating the blog post — it is quite stale, and has since been overtaken by the canonical documentation.

As far as Android-specific aspects, that project (BlabberTabber) is in deep hibernation for the next couple of months, so I have no compelling reason to pursue the Android-angle (though I do find it quite interesting). I was building the Docker container image when the project came to a screeching halt.

—Brian
